
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exataevent
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        run: exataevent
    spec:
      containers:
      - name: exataevent
        image: us.icr.io/iux-miaspace1/iux-events
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082


apiVersion: v1
kind: Service
metadata:
  name: exataevent
  labels:
    run: exataevent
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  type: NodePort
  selector:
    run: exataevent
